#开发环境
server:
  port: 80
jasypt:
  encryptor:
    password: 123
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    primary:
      url: jdbc:mysql://192.168.56.101:3306/ypzhang?characterEncoding=utf-8&serverTimezone=GMT%2B8
      password: zyp
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      url: jdbc:mysql://192.168.56.101:3306/ypzhang2?characterEncoding=utf-8&serverTimezone=GMT%2B8
      password: zyp
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60







